version: "3.9"
services:
  postgres:
    container_name: "postgres"
    image: postgres
    ports:
      - "5332:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
